project:
  type: website

website:
  title: "Quarto exemple"
  sidebar:
    search: false
    style: "docked"
    contents:
      - plot.ipynb   

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true