project:
  type: website

website:
  title: "Quarto example"
  navbar:
    left:
      - text: Home
      - href: index.qmd
    right:
      - icon: github
        href: https://github.com/seriesl/site_github
  sidebar:
    search: false
    style: "docked"
    contents:
      - plot.ipynb   

format:
  html:
    theme:
      - Darkly
    # css: styles.css
    toc: true